<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="showcameras.xsl" ?>
<!--
	License: CC-BY-SA 3.0

	This work is licensed under a
	Creative Commons Attribution-ShareAlike 3.0 Unported License.

	See more at:
	http://creativecommons.org/licenses/by-sa/3.0/
-->

<!DOCTYPE Cameras [
<!ELEMENT BlackAreas ( Vertical*, Horizontal* ) >

<!ELEMENT Camera ( ID?, CFA?, CFA2?, Crop?, Sensor*, BlackAreas?, Aliases?, Hints?, ColorMatrices? ) >
<!ATTLIST Camera make CDATA #REQUIRED >
<!ATTLIST Camera model CDATA #REQUIRED >
<!ATTLIST Camera supported CDATA #IMPLIED >
<!ATTLIST Camera mode CDATA #IMPLIED >
<!ATTLIST Camera decoder_version CDATA #IMPLIED >

<!ELEMENT Cameras ( Camera+ ) >
<!ATTLIST Cameras version CDATA #IMPLIED >

<!ELEMENT CFA ( Color+ ) >
<!ATTLIST CFA height NMTOKEN #REQUIRED >
<!ATTLIST CFA width NMTOKEN #REQUIRED >

<!ELEMENT CFA2 ( Color*, ColorRow* ) >
<!ATTLIST CFA2 height NMTOKEN #REQUIRED >
<!ATTLIST CFA2 width NMTOKEN #REQUIRED >

<!ELEMENT Color ( #PCDATA ) >
<!ATTLIST Color x NMTOKEN #REQUIRED >
<!ATTLIST Color y NMTOKEN #REQUIRED >

<!ELEMENT ColorRow ( #PCDATA ) >
<!ATTLIST ColorRow y NMTOKEN #REQUIRED >

<!ELEMENT Crop EMPTY >
<!ATTLIST Crop height NMTOKEN #REQUIRED >
<!ATTLIST Crop width NMTOKEN #REQUIRED >
<!ATTLIST Crop x NMTOKEN #REQUIRED >
<!ATTLIST Crop y NMTOKEN #REQUIRED >

<!ELEMENT Horizontal EMPTY >
<!ATTLIST Horizontal height NMTOKEN #REQUIRED >
<!ATTLIST Horizontal y NMTOKEN #REQUIRED >

<!ELEMENT Sensor EMPTY >
<!ATTLIST Sensor white NMTOKEN #REQUIRED >
<!ATTLIST Sensor black NMTOKEN #REQUIRED >
<!ATTLIST Sensor black_colors NMTOKEN #IMPLIED >
<!ATTLIST Sensor iso_list NMTOKENS #IMPLIED >
<!ATTLIST Sensor iso_min NMTOKEN #IMPLIED >
<!ATTLIST Sensor iso_max NMTOKEN #IMPLIED >

<!ELEMENT Vertical EMPTY >
<!ATTLIST Vertical width NMTOKEN #REQUIRED >
<!ATTLIST Vertical x NMTOKEN #REQUIRED >

<!ELEMENT Hints ( Hint+ ) >
<!ELEMENT Hint EMPTY >
<!ATTLIST Hint name CDATA #REQUIRED >
<!ATTLIST Hint value CDATA #REQUIRED >

<!ELEMENT Aliases ( Alias+ ) >
<!ATTLIST Alias id CDATA #IMPLIED >
<!ELEMENT Alias (#PCDATA) >

<!ELEMENT ID (#PCDATA) >
<!ATTLIST ID make CDATA #REQUIRED >
<!ATTLIST ID model CDATA #REQUIRED >

<!ELEMENT ColorMatrices ( ColorMatrix ) >

<!ELEMENT ColorMatrix ( ColorMatrixRow+ ) >
<!ATTLIST ColorMatrix planes NMTOKEN #REQUIRED >

<!ELEMENT ColorMatrixRow ( #PCDATA ) >
<!ATTLIST ColorMatrixRow plane NMTOKEN #REQUIRED >

]>

<Cameras>
	<Camera make="ARRI" model="ALEXA" supported="no-samples">
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">RED</Color>
			<Color x="0" y="1">BLUE</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="4095"/>
	</Camera>
	<Camera make="Canon" model="Canon EOS 100D">
		<ID make="Canon" model="EOS 100D">Canon EOS 100D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="72" y="52" width="0" height="0"/>
		<BlackAreas>
			<Vertical x="0" width="72"/>
			<Horizontal y="8" height="44"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel SL1">Canon EOS REBEL SL1</Alias>
			<Alias id="EOS Kiss X7">Canon EOS Kiss X7</Alias>
		</Aliases>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6602 -841 -939</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4472 12458 2247</ColorMatrixRow>
				<ColorMatrixRow plane="2">-975 2039 6148</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 200D">
		<ID make="Canon" model="EOS 200D">Canon EOS 200D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="266" y="42" width="-6" height="-4"/>
		<BlackAreas>
			<Vertical x="0" width="260"/>
			<Horizontal y="0" height="38"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel SL2">Canon EOS Rebel SL2</Alias>
			<Alias id="EOS Kiss X9">Canon EOS Kiss X9</Alias>
		</Aliases>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">7377 -742 -998</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4235 11981 2549</ColorMatrixRow>
				<ColorMatrixRow plane="2">-673 1918 5538</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 300D DIGITAL">
		<ID make="Canon" model="EOS 300D">Canon EOS 300D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="64" y="12" width="0" height="0"/>
		<Sensor black="126" white="4000"/>
		<Sensor black="127" white="4000" iso_list="200"/>
		<Sensor black="128" white="4000" iso_list="400"/>
		<Sensor black="129" white="4000" iso_list="800"/>
		<Sensor black="251" white="4000" iso_list="1600"/>
		<Sensor black="250" white="4000" iso_list="3200"/>
		<BlackAreas>
			<Vertical x="6" width="58"/>
			<Horizontal y="4" height="8"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Digital Rebel">Canon EOS DIGITAL REBEL</Alias>
			<Alias id="EOS Kiss Digital">Canon EOS Kiss Digital</Alias>
		</Aliases>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">8197 -2000 -1118</ColorMatrixRow>
				<ColorMatrixRow plane="1">-6714 14335 2592</ColorMatrixRow>
				<ColorMatrixRow plane="2">-2536 3178 8266</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS D30">
		<ID make="Canon" model="EOS D30">Canon EOS D30</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="52" y="10" width="0" height="-6"/>
		<Sensor black="126" white="4095"/>
		<BlackAreas>
			<Vertical x="0" width="48"/>
			<Horizontal y="0" height="5"/>
		</BlackAreas>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">9805 -2689 -1312</ColorMatrixRow>
				<ColorMatrixRow plane="1">-5803 13064 3068</ColorMatrixRow>
				<ColorMatrixRow plane="2">-2438 3075 8775</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS D60">
		<ID make="Canon" model="EOS D60">Canon EOS D60</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="68" y="18" width="-4" height="-4"/>
		<Sensor black="127" white="4000"/>
		<BlackAreas>
			<Vertical x="16" width="48"/>
			<Horizontal y="12" height="0"/>
		</BlackAreas>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6188 -1341 -890</ColorMatrixRow>
				<ColorMatrixRow plane="1">-7168 14489 2937</ColorMatrixRow>
				<ColorMatrixRow plane="2">-2640 3228 8483</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 10D">
		<ID make="Canon" model="EOS 10D">Canon EOS 10D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="64" y="12" width="0" height="0"/>
		<Sensor black="130" white="4000"/>
		<Sensor black="255" white="4000" iso_list="1600 3200"/>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">8197 -2000 -1118</ColorMatrixRow>
				<ColorMatrixRow plane="1">-6714 14335 2592</ColorMatrixRow>
				<ColorMatrixRow plane="2">-2536 3178 8266</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 20D">
		<ID make="Canon" model="EOS 20D">Canon EOS 20D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="74" y="12" width="3522" height="2348"/>
		<Sensor black="126" white="4095"/>
		<BlackAreas>
			<Vertical x="0" width="72"/>
			<Horizontal y="2" height="8"/>
		</BlackAreas>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6599 -537 -891</ColorMatrixRow>
				<ColorMatrixRow plane="1">-8071 15783 2424</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1983 2234 7462</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 30D">
		<ID make="Canon" model="EOS 30D">Canon EOS 30D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="74" y="12" width="3522" height="2348"/>
		<Sensor black="127" white="3398"/>
		<BlackAreas>
			<Vertical x="0" width="72"/>
			<Horizontal y="2" height="8"/>
		</BlackAreas>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6257 -303 -1000</ColorMatrixRow>
				<ColorMatrixRow plane="1">-7880 15621 2396</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1714 1904 7046</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 350D DIGITAL">
		<ID make="Canon" model="EOS 350D">Canon EOS 350D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="42" y="14" width="3474" height="2314"/>
		<Sensor black="255" white="4095"/>
		<BlackAreas>
			<Vertical x="0" width="40"/>
			<Horizontal y="0" height="12"/>
		</BlackAreas>
		<Aliases>
			<Alias id="Digital Rebel XT">Canon EOS DIGITAL REBEL XT</Alias>
			<Alias id="Kiss Digital N">Canon EOS Kiss Digital N</Alias>
			<Alias id="EOS 350D">Canon EOS 350D</Alias>
			<Alias id="EOS 350D">Canon EOS 350D Digital</Alias>
		</Aliases>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6018 -617 -965</ColorMatrixRow>
				<ColorMatrixRow plane="1">-8645 15881 2975</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1530 1719 7642</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 40D" decoder_version="2">
		<ID make="Canon" model="EOS 40D">Canon EOS 40D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="30" y="18" width="3908" height="2602"/>
		<BlackAreas>
			<Vertical x="0" width="28"/>
			<Horizontal y="4" height="12"/>
		</BlackAreas>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6071 -747 -856</ColorMatrixRow>
				<ColorMatrixRow plane="1">-7653 15365 2441</ColorMatrixRow>
				<ColorMatrixRow plane="2">-2025 2553 7315</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 40D" mode="sRaw1">
		<ID make="Canon" model="EOS 40D">Canon EOS 40D</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Hints>
			<Hint name="sraw_40d" value=""/>
		</Hints>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6071 -747 -856</ColorMatrixRow>
				<ColorMatrixRow plane="1">-7653 15365 2441</ColorMatrixRow>
				<ColorMatrixRow plane="2">-2025 2553 7315</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 40D" mode="sRaw2">
		<ID make="Canon" model="EOS 40D">Canon EOS 40D</ID>
		<Crop x="0" y="0" width="1944" height="1296"/>
		<Hints>
			<Hint name="sraw_40d" value=""/>
		</Hints>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6071 -747 -856</ColorMatrixRow>
				<ColorMatrixRow plane="1">-7653 15365 2441</ColorMatrixRow>
				<ColorMatrixRow plane="2">-2025 2553 7315</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 450D">
		<ID make="Canon" model="EOS 450D">Canon EOS 450D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="22" y="18" width="4290" height="2856"/>
		<Aliases>
			<Alias id="Digital Rebel XSi">Canon EOS DIGITAL REBEL XSi</Alias>
			<Alias id="Kiss Digital X2">Canon EOS Kiss Digital X2</Alias>
			<Alias id="Kiss X2">Canon EOS Kiss X2</Alias>
		</Aliases>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">5784 -262 -821</ColorMatrixRow>
				<ColorMatrixRow plane="1">-7539 15064 2672</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1982 2681 7427</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 50D" decoder_version="1">
		<ID make="Canon" model="EOS 50D">Canon EOS 50D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">BLUE</Color>
			<Color x="0" y="1">RED</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="64" y="52" width="4752" height="3158"/>
		<BlackAreas>
			<Vertical x="0" width="60"/>
			<Horizontal y="2" height="46"/>
		</BlackAreas>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">4920 616 -593</ColorMatrixRow>
				<ColorMatrixRow plane="1">-6493 13964 2784</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1774 3178 7005</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 50D" mode="sRaw1">
		<ID make="Canon" model="EOS 50D">Canon EOS 50D</ID>
		<Crop x="0" y="0" width="3272" height="2178"/>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">4920 616 -593</ColorMatrixRow>
				<ColorMatrixRow plane="1">-6493 13964 2784</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1774 3178 7005</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 50D" mode="sRaw2">
		<ID make="Canon" model="EOS 50D">Canon EOS 50D</ID>
		<Crop x="0" y="0" width="2376" height="1584"/>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">4920 616 -593</ColorMatrixRow>
				<ColorMatrixRow plane="1">-6493 13964 2784</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1774 3178 7005</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 60D" decoder_version="1">
		<ID make="Canon" model="EOS 60D">Canon EOS 60D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">BLUE</Color>
			<Color x="0" y="1">RED</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="146" y="54" width="0" height="0"/>
		<BlackAreas>
			<Vertical x="0" width="140"/>
			<Horizontal y="4" height="46"/>
		</BlackAreas>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6719 -994 -925</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4408 12426 2211</ColorMatrixRow>
				<ColorMatrixRow plane="2">-887 2129 6051</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 60D" mode="sRaw1">
		<ID make="Canon" model="EOS 60D">Canon EOS 60D</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6719 -994 -925</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4408 12426 2211</ColorMatrixRow>
				<ColorMatrixRow plane="2">-887 2129 6051</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 60D" mode="sRaw2">
		<ID make="Canon" model="EOS 60D">Canon EOS 60D</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6719 -994 -925</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4408 12426 2211</ColorMatrixRow>
				<ColorMatrixRow plane="2">-887 2129 6051</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 70D" decoder_version="1">
		<ID make="Canon" model="EOS 70D">Canon EOS 70D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="72" y="38" width="0" height="0"/>
		<BlackAreas>
			<Vertical x="0" width="72"/>
			<Horizontal y="0" height="38"/>
		</BlackAreas>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">7034 -804 -1014</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4420 12564 2058</ColorMatrixRow>
				<ColorMatrixRow plane="2">-851 1994 5758</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 70D" mode="sRaw1">
		<ID make="Canon" model="EOS 70D">Canon EOS 70D</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Hints>
			<Hint name="sraw_new" value=""/>
			<Hint name="invert_sraw_wb" value=""/>
		</Hints>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">7034 -804 -1014</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4420 12564 2058</ColorMatrixRow>
				<ColorMatrixRow plane="2">-851 1994 5758</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 70D" mode="sRaw2">
		<ID make="Canon" model="EOS 70D">Canon EOS 70D</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Hints>
			<Hint name="sraw_new" value=""/>
			<Hint name="invert_sraw_wb" value=""/>
		</Hints>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">7034 -804 -1014</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4420 12564 2058</ColorMatrixRow>
				<ColorMatrixRow plane="2">-851 1994 5758</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 80D">
		<ID make="Canon" model="EOS 80D">Canon EOS 80D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="266" y="42" width="-8" height="-4"/>
		<BlackAreas>
			<Vertical x="0" width="263"/>
			<Horizontal y="0" height="33"/>
		</BlackAreas>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">7457 -671 -937</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4849 12495 2643</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1213 2354 5492</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 80D" mode="sRaw1" decoder_version="8">
		<ID make="Canon" model="EOS 80D">Canon EOS 80D</ID>
		<Crop x="28" y="10" width="0" height="0"/>
		<Hints>
			<Hint name="sraw_new" value=""/>
			<Hint name="invert_sraw_wb" value=""/>
		</Hints>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">7457 -671 -937</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4849 12495 2643</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1213 2354 5492</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 80D" mode="sRaw2" decoder_version="7">
		<ID make="Canon" model="EOS 80D">Canon EOS 80D</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Hints>
			<Hint name="sraw_new" value=""/>
			<Hint name="invert_sraw_wb" value=""/>
		</Hints>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">7457 -671 -937</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4849 12495 2643</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1213 2354 5492</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 700D">
		<ID make="Canon" model="EOS 700D">Canon EOS 700D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="76" y="60" width="-6" height="-6"/>
		<BlackAreas>
			<Vertical x="0" width="70"/>
			<Horizontal y="4" height="50"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel T5i">Canon EOS REBEL T5i</Alias>
			<Alias id="EOS Kiss X7i">Canon EOS Kiss X7i</Alias>
		</Aliases>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6602 -841 -939</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4472 12458 2247</ColorMatrixRow>
				<ColorMatrixRow plane="2">-975 2039 6148</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 750D">
		<ID make="Canon" model="EOS 750D">Canon EOS 750D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="72" y="34" width="0" height="0"/>
		<Aliases>
			<Alias id="EOS Rebel T6i">Canon EOS Rebel T6i</Alias>
			<Alias id="EOS Kiss X8i">Canon EOS Kiss X8i</Alias>
		</Aliases>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6362 -823 -847</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4426 12109 2616</ColorMatrixRow>
				<ColorMatrixRow plane="2">-743 1857 5635</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 800D">
		<ID make="Canon" model="EOS 800D">Canon EOS 800D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="266" y="42" width="-6" height="-4"/>
		<BlackAreas>
			<Vertical x="0" width="260"/>
			<Horizontal y="2" height="36"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel T7i">Canon EOS Rebel T7i</Alias>
			<Alias id="EOS REBEL T7i">Canon EOS REBEL T7i</Alias>
			<Alias id="EOS Kiss X9i">Canon EOS Kiss X9i</Alias>
		</Aliases>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6970 -512 -968</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4425 12161 2553</ColorMatrixRow>
				<ColorMatrixRow plane="2">-739 1982 5601</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 760D">
		<ID make="Canon" model="EOS 760D">Canon EOS 760D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="72" y="34" width="0" height="0"/>
		<Aliases>
			<Alias id="EOS Rebel T6s">Canon EOS Rebel T6s</Alias>
			<Alias id="EOS 8000D">Canon EOS 8000D</Alias>
		</Aliases>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6362 -823 -847</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4426 12109 2616</ColorMatrixRow>
				<ColorMatrixRow plane="2">-743 1857 5635</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 77D">
		<ID make="Canon" model="EOS 77D">Canon EOS 77D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="266" y="42" width="-6" height="-4"/>
		<BlackAreas>
			<Vertical x="0" width="260"/>
			<Horizontal y="2" height="32"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS 9000D">Canon EOS 9000D</Alias>
		</Aliases>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">7377 -742 -998</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4235 11981 2549</ColorMatrixRow>
				<ColorMatrixRow plane="2">-673 1918 5538</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 500D">
		<ID make="Canon" model="EOS 500D">Canon EOS 500D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="62" y="30" width="4722" height="3142"/>
		<BlackAreas>
			<Vertical x="0" width="56"/>
			<Horizontal y="2" height="22"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel T1i">Canon EOS REBEL T1i</Alias>
			<Alias id="EOS Kiss X3">Canon EOS Kiss X3</Alias>
		</Aliases>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">4763 712 -646</ColorMatrixRow>
				<ColorMatrixRow plane="1">-6821 14399 2640</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1921 3276 6561</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 550D">
		<ID make="Canon" model="EOS 550D">Canon EOS 550D</ID>
		<CFA width="2" height="2">
			<Color x="1" y="0">BLUE</Color>
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="1">GREEN</Color>
			<Color x="0" y="1">RED</Color>
		</CFA>
		<Crop x="148" y="54" width="0" height="0"/>
		<BlackAreas>
			<Vertical x="0" width="140"/>
			<Horizontal y="4" height="44"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel T2i">Canon EOS REBEL T2i</Alias>
			<Alias id="EOS Kiss X4">Canon EOS Kiss X4</Alias>
		</Aliases>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6941 -1164 -857</ColorMatrixRow>
				<ColorMatrixRow plane="1">-3825 11597 2534</ColorMatrixRow>
				<ColorMatrixRow plane="2">-416 1540 6039</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 600D">
		<ID make="Canon" model="EOS 600D">Canon EOS 600D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">BLUE</Color>
			<Color x="0" y="1">RED</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="146" y="54" width="0" height="0"/>
		<BlackAreas>
			<Vertical x="0" width="140"/>
			<Horizontal y="4" height="44"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel T3i">Canon EOS REBEL T3i</Alias>
			<Alias id="EOS Kiss X5">Canon EOS Kiss X5</Alias>
		</Aliases>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6461 -907 -882</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4300 12184 2378</ColorMatrixRow>
				<ColorMatrixRow plane="2">-819 1944 5931</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 650D">
		<ID make="Canon" model="EOS 650D">Canon EOS 650D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="76" y="56" width="0" height="0"/>
		<BlackAreas>
			<Vertical x="0" width="70"/>
			<Horizontal y="4" height="44"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel T4i">Canon EOS REBEL T4i</Alias>
			<Alias id="EOS Kiss X6i">Canon EOS Kiss X6i</Alias>
		</Aliases>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6602 -841 -939</ColorMatrixRow>
				<ColorMatrixRow plane="1">-4472 12458 2247</ColorMatrixRow>
				<ColorMatrixRow plane="2">-975 2039 6148</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 5D">
		<ID make="Canon" model="EOS 5D">Canon EOS 5D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="90" y="34" width="4386" height="2920"/>
		<Sensor black="127" white="3692"/>
		<BlackAreas>
			<Vertical x="0" width="88"/>
			<Horizontal y="2" height="30"/>
		</BlackAreas>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">6347 -479 -972</ColorMatrixRow>
				<ColorMatrixRow plane="1">-8297 15954 2480</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1968 2131 7649</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 5D Mark II" decoder_version="1">
		<ID make="Canon" model="EOS 5D Mark II">Canon EOS 5D Mark II</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">BLUE</Color>
			<Color x="0" y="1">RED</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="158" y="51" width="5634" height="3753"/>
		<BlackAreas>
			<Vertical x="0" width="156"/>
			<Horizontal y="2" height="48"/>
		</BlackAreas>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">4716 603 -830</ColorMatrixRow>
				<ColorMatrixRow plane="1">-7798 15474 2480</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1496 1937 6651</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 5D Mark II" mode="sRaw1">
		<ID make="Canon" model="EOS 5D Mark II">Canon EOS 5D Mark II</ID>
		<Crop x="0" y="0" width="3872" height="2574"/>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">4716 603 -830</ColorMatrixRow>
				<ColorMatrixRow plane="1">-7798 15474 2480</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1496 1937 6651</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 5D Mark II" mode="sRaw2">
		<ID make="Canon" model="EOS 5D Mark II">Canon EOS 5D Mark II</ID>
		<Crop x="0" y="0" width="2808" height="1872"/>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">4716 603 -830</ColorMatrixRow>
				<ColorMatrixRow plane="1">-7798 15474 2480</ColorMatrixRow>
				<ColorMatrixRow plane="2">-1496 1937 6651</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera>
	<Camera make="Canon" model="Canon EOS 5D Mark III" decoder_version="2">
		<ID make="Canon" model="EOS 5D Mark III">Canon EOS 5D Mark III</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="124" y="82" width="-2" height="0"/>
		<BlackAreas>
			<Vertical x="0" width="120"/>
			<Horizontal y="2" height="78"/>
		</BlackAreas>